version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: packages/nextjs/Dockerfile
    image: botanix-ln-webapp:latest  
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always

  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    image: botanix-ln-server:latest
    ports:
      - "3003:3003"
    restart: always

